### PR TITLE
XEP-0357 Support

### PR DESCRIPTION
**Pull request by chrisballinger**
There are still some things that could be improved.

Currently on every stream connection it checks for server support of XEP-0357 and re-registers with a new push token. This is probably too aggressive, but it's the least error prone. This push token is not associated with a buddyKey which may cause issues elsewhere, but seems fine so far.

Another issue is that `mod_cloud_notify` is too aggressive when sending push notifications, and will even send them for typing notifications. Since we display "Someone wants to chat" for every received push that doesn't map to a buddy, it can get a little noisy. We can't control the behavior of other XMPP servers so we should address this in the PubSub node and elsewhere in the client.

We will also want to strip as much content as possible in the PubSub node to avoid leaking extraneous incoming data.

### CODE REVIEW

**Comment by chrisballinger** [comment]
This PR resolves https://github.com/ChatSecure/ChatSecure-iOS/issues/367

**Comment by weiss** [comment]
First of all: *yay* for implementing this!

> Currently on every stream connection it checks for server support of XEP-0357 and re-registers with a new push token.

Yes, I see no way to get around this in a reliable way.

> Another issue is that `mod_cloud_notify` is too aggressive when sending push notifications, and will even send them for typing notifications. Since we display "Someone wants to chat" for every received push that doesn't map to a buddy, it can get a little noisy. We can't control the behavior of other XMPP servers so we should address this in the PubSub node and elsewhere in the client.

I think enabling [CSI][1] with (if you're using Prosody) [`mod_filter_chatstates`][2] should do the trick.

FWIW, my idea for XEP-0357 support in ejabberd is to basically follow the [business rules suggested by Daniel][3].

[1]: https://xmpp.org/extensions/xep-0352.html
[2]: https://modules.prosody.im/mod_filter_chatstates.html
[3]: http://mail.jabber.org/pipermail/standards/2016-February/030925.html

**Comment by weiss** [comment]
> I think enabling CSI with (if you're using Prosody) `mod_filter_chatstates` should do the trick.

Oh, `mod_cloud_notify` just notifies on offline messages, right?  Then CSI won't help, of course.  (But I thought chat states [aren't supposed to be written to offline storage][1])?

Either way, I think this would best be solved on the XMPP server side; as I thought ideally, your PubSub node wouldn't even see the stanza payload (and would therefore not be able to filter out notifications based on stanza contents).

[1]: https://xmpp.org/extensions/xep-0160.html#types

**Comment by chrisballinger** [comment]
@weiss We've noticed that `mod_cloud_notify` currently doesn't store the push settings across restarts, so re-registering on every login seems to be necessary.

On a side note, I noticed that when checking the server capabilities for the user's JID, it doesn't show support for push, only when you check the server's JID. Perhaps this should be addressed in the spec.

**Comment by iNPUTmice** [comment]
> Currently on every stream connection it checks for server support of XEP-0357 and re-registers with a new push token. This is probably too aggressive, but it's the least error prone

This is probably a good idea anyway so your server can associate a stream with a specific token and take appropriate action like for example not push for that token if the stream is still alive.

I would strongly suggest to read my [business rules](http://mail.jabber.org/pipermail/standards/2016-February/030925.html) and either follow them or if you disagree comment on the mailing list so we can come to an agreement so all clients and servers do more or less the same thing.

**Comment by iNPUTmice** [comment]
> On a side note, I noticed that when checking the server capabilities for the user's JID, it doesn't show support for push, only when you check the server's JID. Perhaps this should be addressed in the spec.

The spec is actually pretty clear. It's prosody that should change the behavior here. (FWIW Conversations is checking both. The server and the accounts disco)

**Comment by chrisballinger** [comment]
Yeah we check for both as well.

**Pull request merged**
