### PR TITLE
macOS Support [WIP]

### PR DESCRIPTION
**Pull request by chrisballinger**
Turns out getting it up and running via "Project Catalyst" wasn't too difficult. There are a lot of rough edges but it works.
Screen Shot 2019-06-06 at 9 47 53 PM

### CODE REVIEW

**Comment by anurodhp** [comment]
thanks,  I am in the process of doing the same thing!

**Comment by myzinsky** [comment]
New macOS is out? When can we have it :)

**Comment by myzinsky** [comment]
Any news?

**Comment by chrisballinger** [comment]
@myzinsky It was blocked for a while on Apple's crypto export review. Took them over a month. Should be unblocked now.

**Comment by myzinsky** [comment]
I mean when will it be in the App-Store :)

**Comment by chrisballinger** [comment]
No ETA but possibly by end of 2019, or early 2020

**Comment by chrisballinger** [comment]
Superceded by #1155

**Pull request closed without merging**
